/** Перечисления склада с русскими подписями — для селектов в UI (GET /warehouse/meta). */
export const WAREHOUSE_META = {
  docTypes: [
    { value: 'RECEIPT', label: 'Приход' },
    { value: 'TRANSFER', label: 'Перемещение' },
    { value: 'ISSUE', label: 'Выдача' },
    { value: 'WRITE_OFF', label: 'Списание' },
    { value: 'RETURN', label: 'Возврат' },
    { value: 'INVENTORY', label: 'Инвентаризация' },
    { value: 'CORRECTION', label: 'Корректировка' },
    { value: 'DEFECT', label: 'Брак' },
  ],
  docStatuses: [
    { value: 'DRAFT', label: 'Черновик' },
    { value: 'PENDING_APPROVAL', label: 'На согласовании' },
    { value: 'APPROVED', label: 'Согласован' },
    { value: 'IN_PROGRESS', label: 'В работе' },
    { value: 'SHIPPED', label: 'В пути' },
    { value: 'RECEIVED', label: 'Получен' },
    { value: 'POSTED', label: 'Проведён' },
    { value: 'REJECTED', label: 'Отклонён' },
    { value: 'CANCELLED', label: 'Отменён' },
  ],
  writeOffReasons: [
    { value: 'USED', label: 'Использовано в работе' },
    { value: 'SPOILAGE', label: 'Порча' },
    { value: 'BREAKAGE', label: 'Бой' },
    { value: 'WEAR', label: 'Износ' },
    { value: 'LOSS', label: 'Утеря' },
    { value: 'THEFT', label: 'Кража' },
    { value: 'EXPIRED', label: 'Просрочка' },
    { value: 'DEFECT', label: 'Брак' },
    { value: 'GIVEN_TO_GUEST', label: 'Передано гостю' },
    { value: 'OTHER', label: 'Другое' },
  ],
  normUnits: [
    { value: 'ROOM_NIGHT', label: 'номеро-сутки' },
    { value: 'STAY', label: 'заезд' },
    { value: 'GUEST', label: 'гость' },
    { value: 'CLEANING', label: 'уборка' },
    { value: 'PLACE', label: 'место' },
    { value: 'MONTH', label: 'месяц' },
  ],
  addressTypes: [
    { value: 'APARTMENTS', label: 'Апартаменты' },
    { value: 'MINI_HOTEL', label: 'Мини-отель' },
    { value: 'HOTEL', label: 'Отель' },
    { value: 'OFFICE', label: 'Офис' },
    { value: 'OTHER', label: 'Другое' },
  ],
  warehouseTypes: [
    { value: 'CENTRAL', label: 'Центральный склад' },
    { value: 'ADDRESS_LOCAL', label: 'Локальный склад адреса' },
    { value: 'SUBDIVISION_VIRTUAL', label: 'Виртуальный склад подразделения' },
    { value: 'WRITE_OFF', label: 'Склад списания' },
    { value: 'DEFECT', label: 'Склад брака' },
  ],
} as const;
